### ISSUE TITLE
[Unresolved] Conflicting booking overwrites existing booking

### ISSUE THREAD

**Issue by SeekSaveServe** [usdevs/uscwebsite-hackathon-backend#75]
Fiqri's booking was replaced by the booking by Daniel and Table Tennis despite them being conflicting bookings. We could not find a way to resolve this or why it happened. 

![photo_2023-09-04_10-15-34](https://github.com/usdevs/uscwebsite-hackathon-backend/assets/53963433/4fc048dc-95ef-4721-9f1a-463fa58d00bd)
<img width="405" alt="Screenshot_1" src="https://github.com/usdevs/uscwebsite-hackathon-backend/assets/53963433/39191d6b-1875-42c2-a64b-9d7f0e33aa48">
<img width="450" alt="Screenshot_2" src="https://github.com/usdevs/uscwebsite-hackathon-backend/assets/53963433/f2a83f4d-bec0-4aea-a599-ba295d3fb9e9">

**Comment by parth-io** [comment]
Feel free to close this issue once logging is set up

**Comment by zsh-eng** [comment]
Logging has been set up in #96. Issue will be closed for now. Can consider re-opening if the bug surfaces again in the future.
